

spring:
  application:
    name: b2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: malldbuser
    password: malldbuser
    url: jdbc:mariadb://localhost:3306/malldb
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3f4ce98855a784c09a4ac2af250d48f4
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, profile_image #동의 항목
            client-name: Kakao
            client-secret: hblMrwoDi4ZtbV3lsLQnvp419tIutPFH
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-file-size: 2MB
      max-request-size: 20MB

logging:
  level:
    com.zaxxer: debug
    org.springframework.jdbc: debug
    org.springframework.security: trace
    org:
      apache:
        ibatis: debug

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.zerock.b2.**.dto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


board:
  upload: C:\\upload\\attach
